#port: 7890
#socks-port: 7891
#redir-port: 7892
#tproxy-port: 7893
mixed-port: 7890

#authentication:
# - "user1:pass1"
# - "user2:pass2"

allow-lan: false
bind-address: '*'
mode: rule
log-level: info
ipv6: false

external-controller: 127.0.0.1:9090
#external-ui: yacd

#secret: ""

#interface-name: en0

hosts:
  #'*.clash.dev': 127.0.0.1
  #'.dev': 127.0.0.1
  #'alpha.clash.dev': '::1'

profile:
  store-selected: true

# ## tun
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    # ## 国内服务器
    - 119.29.29.29    # 腾讯
    #- 223.5.5.5       # 阿里
    #- 180.76.76.76    # 百度
    # ## 真实请求DNS
    - 114.114.114.114 # 真实请求DNS，可多设置几个
    #- 8.8.8.8
  enhanced-mode: fake-ip
  nameserver:
    # ## 国内服务器
    - 119.29.29.29    # 腾讯
    #- 223.5.5.5       # 阿里
    #- 180.76.76.76    # 百度
    # ## 真实请求DNS
    - 114.114.114.114 # 真实请求DNS，可多设置几个
    #- 8.8.8.8
    # ## Others
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS
    - dhcp://en0 # dns from dhcp
  fallback:
      - https://8888.google/dns-query
      - https://1.0.0.1/dns-query
      - https://dns.twnic.tw/dns-query
      - https://doh.opendns.com/dns-query
      - https://dns-nyc.aaflalo.me/dns-query
      - https://dns.aa.net.uk/dns-query
      - https://sg.adhole.org/dns-query
      - https://kaitain.restena.lu/dns-query
      - https://hydra.plan9-ns1.com/dns-query
      - https://jp.tiar.app/dns-query
      - https://doh.asia.dnswarden.com/adblock
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - "+.github.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"

tun:
  enable: true
  stack: system # or gvisor
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true # conflict with interface-name

proxy-groups:
  - name: "LastMatch"
    type: select
    proxies:
      - DIRECT
      - Entry

  - name: "Entry"
    type: select
    proxies:
      - AllAuto
      - AllFallback
      - MainSelect
    url: 'https://www.gstatic.com/generate_204'
    interval: 300

  - name: "Entry-ChatGpt"
    type: select
    proxies:
      - ChatGptAuto
      - ChatGptSelect
    url: 'https://chat.openai.com'
    interval: 300

  - name: "AllAuto"
    type: url-test
    proxies:
      - MainAuto
    url: 'https://www.gstatic.com/generate_204'
    interval: 30

  - name: "AllFallback"
    type: fallback
    proxies:
      - MainAuto
    url: 'https://www.gstatic.com/generate_204'
    interval: 30

  - name: "ChatGptSelect"
    type: select
    use:
      - main
    url: 'https://chat.openai.com'
    interval: 300

  - name: "MainSelect"
    type: select
    use:
      - main
    url: 'https://www.gstatic.com/generate_204'
    interval: 300

  - name: "MainAuto"
    type: url-test
    use:
      - main
    url: 'https://www.gstatic.com/generate_204'
    interval: 300

  - name: "ChatGptAuto"
    type: url-test
    use:
      - main
    url: 'https://chat.openai.com'
    interval: 300

proxy-providers:
  main:
    type: http
    url: "<your url>"
    path: ./proxy-providers/NodeList/main.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 600
      url: https://www.gstatic.com/generate_204

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 21600

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 21600

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 21600

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 21600

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 21600

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 21600

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 21600

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 21600

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 21600

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 21600

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 21600

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 21600

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 21600

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 21600

rules:
  # ## Basic
  #- PROCESS-NAME,v2ray,DIRECT
  #- PROCESS-NAME,v2ray.exe,DIRECT
  - PROCESS-NAME,FeiQ.exe,DIRECT
  - DOMAIN,cdn.jsdelivr.net,Entry
  - DOMAIN,cdn.sstatic.net,Entry
  - DOMAIN-SUFFIX,githubusercontent.com,Entry
  - DOMAIN-SUFFIX,hcaptcha.com,Entry
  - DOMAIN-SUFFIX,captcha.website,Entry
  - DOMAIN-SUFFIX,altapps.net,Entry
  #- DOMAIN,packages.chocolatey.org,Entry
  - DOMAIN-SUFFIX,chocolatey.org,Entry
  #- DOMAIN-SUFFIX,scoop.sh,Entry
  - DOMAIN-SUFFIX,live.com,Entry
  - DOMAIN-SUFFIX,openai.com,Entry-ChatGpt
  - DOMAIN-SUFFIX,cn.bing.com,DIRECT
  - DOMAIN-SUFFIX,bing.com,Entry

  # ## 订阅转换
  - DOMAIN-SUFFIX,bianyuan.xyz,Entry
  - DOMAIN-SUFFIX,suo.yt,Entry
  - DOMAIN-SUFFIX,sub.xeton.dev,Entry
  - DOMAIN-SUFFIX,pub-api-1.bianyuan.xyz,Entry
  - DOMAIN-SUFFIX,sub.id9.cc,Entry
  # ## 大流量
  - DOMAIN-SUFFIX,youtube.com,Entry
  - DOMAIN-SUFFIX,googlevideo.com,Entry
  - DOMAIN-KEYWORD,tiktok,Entry
  # ## 编程或学习相关
  - DOMAIN,debuginfod.archlinux.org,Entry
  - DOMAIN-SUFFIX,stackexchange.com,Entry
  - DOMAIN-SUFFIX,superuser.com,Entry
  - DOMAIN-SUFFIX,askubuntu.com,Entry
  - DOMAIN-SUFFIX,pythontutor.com,Entry
  - DOMAIN-SUFFIX,cppreference.com,Entry
  - DOMAIN-SUFFIX,modernescpp.com,Entry
  - DOMAIN-SUFFIX,boost.org,Entry
  - DOMAIN-SUFFIX,rust-lang.org,Entry
  - DOMAIN-SUFFIX,rustwiki.org,Entry
  - DOMAIN-SUFFIX,wangchujiang.com,Entry
  - DOMAIN-SUFFIX,leetcode.com,Entry
  - DOMAIN-SUFFIX,greasyfork.org,Entry
  - DOMAIN-SUFFIX,qt.io,Entry
  - DOMAIN-SUFFIX,wordhippo.com,Entry
  - DOMAIN-SUFFIX,deepl.com,Entry
  # ## 科学上网
  - DOMAIN-SUFFIX,v2rayse.com,Entry
  - DOMAIN-SUFFIX,herokuapp.com,Entry
  - DOMAIN-SUFFIX,bulink.xyz,Entry
  - DOMAIN-SUFFIX,yugogo.xyz,Entry
  - DOMAIN-SUFFIX,sspool.nl,Entry
  - DOMAIN-SUFFIX,bihai.cf,Entry
  - DOMAIN-SUFFIX,kingfu.cf,Entry
  - DOMAIN-SUFFIX,swyjq.com,Entry
  - DOMAIN-SUFFIX,hax.co.id,Entry
  # ## Common
  - DOMAIN-KEYWORD,speedtest,Entry
  - DOMAIN-SUFFIX,rutracker.org,Entry
  - DOMAIN-SUFFIX,truthsocial.com,Entry
  - DOMAIN-SUFFIX,musclewiki.com,Entry
  # ## Temp
  - DOMAIN-SUFFIX,lukesmith.xyz,Entry

  # ## Clash rules
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,Entry
  - RULE-SET,gfw,Entry
  - RULE-SET,greatfire,Entry
  - RULE-SET,telegramcidr,Entry
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT

  # ## Rule mode
  - MATCH,LastMatch
