#port: 7890
#socks-port: 7891
#redir-port: 7892
#tproxy-port: 7893
mixed-port: 7890

#authentication:
# - "user1:pass1"
# - "user2:pass2"

allow-lan: false
bind-address: '*'
mode: rule
log-level: info
ipv6: false

external-controller: 127.0.0.1:9090
external-ui: yacd

#secret: ""

#interface-name: en0

hosts:
  #'*.clash.dev': 127.0.0.1
  #'.dev': 127.0.0.1
  #'alpha.clash.dev': '::1'

profile:
  store-selected: true

# ## tun
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    # ## 国内服务器
    - 119.29.29.29    # 腾讯
    #- 223.5.5.5       # 阿里
    #- 180.76.76.76    # 百度
    # ## 真实请求DNS
    - 114.114.114.114 # 真实请求DNS，可多设置几个
    #- 8.8.8.8
  enhanced-mode: fake-ip
  nameserver:
    # ## 国内服务器
    - 119.29.29.29    # 腾讯
    #- 223.5.5.5       # 阿里
    #- 180.76.76.76    # 百度
    # ## 真实请求DNS
    - 114.114.114.114 # 真实请求DNS，可多设置几个
    #- 8.8.8.8
    # ## Others
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS
    - dhcp://en0 # dns from dhcp
  fallback:
      - https://8888.google/dns-query
      - https://1.0.0.1/dns-query
      - https://dns.twnic.tw/dns-query
      - https://doh.opendns.com/dns-query
      - https://dns-nyc.aaflalo.me/dns-query
      - https://dns.aa.net.uk/dns-query
      - https://sg.adhole.org/dns-query
      - https://kaitain.restena.lu/dns-query
      - https://hydra.plan9-ns1.com/dns-query
      - https://jp.tiar.app/dns-query
      - https://doh.asia.dnswarden.com/adblock
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - "+.github.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"

tun:
  enable: true
  stack: system # or gvisor
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true # conflict with interface-name

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - AllAuto
      - AllFallback
      - AllSelect
      - NodePoolAuto-Primary
      - NodePoolAuto-Secondary
      - NodePoolAuto-Relay
      - NodePoolAuto-CN
      - NodePoolAuto-Extra
    url: 'https://www.gstatic.com/generate_204'
    interval: 300

  - name: "RuleMode"
    type: select
    proxies:
      - DIRECT
      - Proxy

  - name: "AllAuto"
    type: url-test
    proxies:
      - NodePoolAuto-Primary
      - NodePoolAuto-Secondary
      - NodePoolAuto-Relay
      - NodePoolAuto-Extra
      - NodePoolAuto-CN
    url: 'https://www.gstatic.com/generate_204'
    interval: 30

  - name: "AllFallback"
    type: fallback
    proxies:
      - NodePoolAuto-Primary
      - NodePoolAuto-Secondary
      - NodePoolAuto-Relay
      - NodePoolAuto-Extra
      - NodePoolAuto-CN
    url: 'https://www.gstatic.com/generate_204'
    interval: 30

  - name: "AllSelect"
    type: select
    use:
      - nodepool-primary
      - nodepool-secondary
      - nodepool-relay
      - nodepool-cn
      - nodepool-extra
    url: 'https://www.gstatic.com/generate_204'
    interval: 300

  - name: "NodePoolAuto-CN"
    type: url-test
    use:
      - nodepool-cn
    url: 'https://www.gstatic.com/generate_204'
    interval: 300

  - name: "NodePoolAuto-Primary"
    type: url-test
    use:
      - nodepool-primary
    url: 'https://www.gstatic.com/generate_204'
    interval: 300

  - name: "NodePoolAuto-Secondary"
    type: url-test
    use:
      - nodepool-secondary
    url: 'https://www.gstatic.com/generate_204'
    interval: 300

  - name: "NodePoolAuto-Relay"
    type: url-test
    use:
      - nodepool-relay
    url: 'https://www.gstatic.com/generate_204'
    interval: 300

  - name: "NodePoolAuto-Extra"
    type: url-test
    use:
      - nodepool-extra
    url: 'https://www.gstatic.com/generate_204'
    interval: 300

proxy-providers:
  nodepool-cn:
    type: http
    #url: "https://sspool.herokuapp.com/clash/proxies?c=CN,HK,TW,MO"
    url: "https://proxies.bihai.cf/clash/proxies?c=CN,HK,TW,MO&filter=nrp"
    path: ./proxy-providers/nodepool/cn.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 600
      url: https://www.gstatic.com/generate_204

  nodepool-primary:
    type: http
    #url: "https://sspool.herokuapp.com/clash/proxies?type=vmess,ssr,trojan&c=SG,CA,RU,AU,CH,DE,FR,GD,NL,JP,US"
    url: "https://proxies.bihai.cf/clash/proxies?type=vmess,ssr,trojan&c=SG,CA,RU,AU,CH,DE,FR,GD,NL,JP,US&filter=nrp"
    path: ./proxy-providers/nodepool/primary.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 600
      url: https://www.gstatic.com/generate_204

  nodepool-secondary:
    type: http
    #url: "https://sspool.herokuapp.com/clash/proxies?type=vmess,ssr,trojan&c=AD,AE,AF,AG,AI,AL,AM,AN,AO,AQ,AR,ARPA,AS,AT,AW,AZ,BA,BB,BD,BE,BF,BG,BH,BI,BJ,BM,BN,BO,BR,BS,BT,BV,BW,BY,BZ,CC,CF,CD,CG,CI,CK,CL,CM,CO,COM,CR,CS,CU,CV,CX,CY,CZ,DJ,DK,DM,DO,DZ,EC,EDU,EE,EG,EH,ER,ES,ET,FI,FJ,FK,FM,FO,FX,GA,GB,GE,GF,GH,GI,GL,GM,GN,GOV,GP,GQ,GR,GS,GT,GU,GW,GY,HM,HN,HR,HT,HU,ID,IE,IL,IN,INT,IO,IQ,IR,IS,IT,JM,JO,KE,KG,KH,KI,KM,KN,KP,KR,KW,KY,KZ,LA,LB,LC,LI,LK,LR,LS,LT,LU,LV,LY,MA,MC,MD,MG,MH,MIL,MK,ML,MM,MN,MP,MQ,MR,MS,MT,MU,MV,MW,MX,MY,MZ,NA,NATO,NC,NE,NET,NF,NG,NI,NO,NP,NR,NT,NU,NZ,OM,ORG,PA,PE,PF,PG,PH,PK,PL,PM,PN,PR,PT,PW,PY,QA,RE,RO,RW,SA,SB,SC,SD,SE,SH,SI,SJ,SK,SL,SM,SN,SO,SR,ST,SU,SV,SY,SZ,TC,TD,TF,TG,TH,TJ,TK,TM,TN,TO,TP,TR,TT,TV,TZ,UA,UG,UK,UM,UY,UZ,VA,VC,VE,VG,VI,VN,VU,WF,WS,YE,YT,YU,ZA,ZM,ZR,ZW"
    url: "https://proxies.bihai.cf/clash/proxies?type=vmess,ssr,trojan&c=AD,AE,AF,AG,AI,AL,AM,AN,AO,AQ,AR,ARPA,AS,AT,AW,AZ,BA,BB,BD,BE,BF,BG,BH,BI,BJ,BM,BN,BO,BR,BS,BT,BV,BW,BY,BZ,CC,CF,CD,CG,CI,CK,CL,CM,CO,COM,CR,CS,CU,CV,CX,CY,CZ,DJ,DK,DM,DO,DZ,EC,EDU,EE,EG,EH,ER,ES,ET,FI,FJ,FK,FM,FO,FX,GA,GB,GE,GF,GH,GI,GL,GM,GN,GOV,GP,GQ,GR,GS,GT,GU,GW,GY,HM,HN,HR,HT,HU,ID,IE,IL,IN,INT,IO,IQ,IR,IS,IT,JM,JO,KE,KG,KH,KI,KM,KN,KP,KR,KW,KY,KZ,LA,LB,LC,LI,LK,LR,LS,LT,LU,LV,LY,MA,MC,MD,MG,MH,MIL,MK,ML,MM,MN,MP,MQ,MR,MS,MT,MU,MV,MW,MX,MY,MZ,NA,NATO,NC,NE,NET,NF,NG,NI,NO,NP,NR,NT,NU,NZ,OM,ORG,PA,PE,PF,PG,PH,PK,PL,PM,PN,PR,PT,PW,PY,QA,RE,RO,RW,SA,SB,SC,SD,SE,SH,SI,SJ,SK,SL,SM,SN,SO,SR,ST,SU,SV,SY,SZ,TC,TD,TF,TG,TH,TJ,TK,TM,TN,TO,TP,TR,TT,TV,TZ,UA,UG,UK,UM,UY,UZ,VA,VC,VE,VG,VI,VN,VU,WF,WS,YE,YT,YU,ZA,ZM,ZR,ZW&filter=nrp"
    path: ./proxy-providers/nodepool/secondary.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 600
      url: https://www.gstatic.com/generate_204

  nodepool-relay:
    type: http
    #url: "https://proxy.yugogo.xyz/clash/proxies?filter=1"
    url: "https://proxies.bihai.cf/clash/proxies?filter=r"
    path: ./proxy-providers/nodepool/relay.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 600
      url: https://www.gstatic.com/generate_204

  nodepool-extra:
    type: http
    url: "https://suo.yt/XV9Ac7n"
    path: ./proxy-providers/nodepool/extra.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 600
      url: https://www.gstatic.com/generate_204

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  # ## Basic
  #- PROCESS-NAME,v2ray,DIRECT
  #- PROCESS-NAME,v2ray.exe,DIRECT
  - DOMAIN,cdn.jsdelivr.net,Proxy
  - DOMAIN,githubusercontent.com,Proxy
  - DOMAIN-SUFFIX,hcaptcha.com,Proxy
  - DOMAIN-SUFFIX,captcha.website,Proxy
  - DOMAIN-SUFFIX,altapps.net,Proxy
  #- DOMAIN,packages.chocolatey.org,Proxy
  - DOMAIN-SUFFIX,chocolatey.org,Proxy
  #- DOMAIN-SUFFIX,scoop.sh,Proxy

  # ## 订阅转换
  - DOMAIN-SUFFIX,bianyuan.xyz,Proxy
  - DOMAIN-SUFFIX,suo.yt,Proxy
  - DOMAIN-SUFFIX,sub.xeton.dev,Proxy
  - DOMAIN-SUFFIX,pub-api-1.bianyuan.xyz,Proxy
  - DOMAIN-SUFFIX,sub.id9.cc,Proxy
  # ## 大流量
  - DOMAIN,release.dreamacro.workers.dev,Proxy
  - DOMAIN-SUFFIX,uptodown.com,Proxy
  - DOMAIN-SUFFIX,tiktokcdn.com,Proxy
  - DOMAIN-SUFFIX,imj6.com,Proxy
  # ## 编程或学习相关
  - DOMAIN,debuginfod.archlinux.org,Proxy
  - DOMAIN-SUFFIX,pythontutor.com,Proxy
  - DOMAIN-SUFFIX,cppreference.com,Proxy
  - DOMAIN-SUFFIX,modernescpp.com,Proxy
  - DOMAIN-SUFFIX,boost.org,Proxy
  - DOMAIN-SUFFIX,rust-lang.org,Proxy
  - DOMAIN-SUFFIX,rustwiki.org,Proxy
  - DOMAIN-SUFFIX,wangchujiang.com,Proxy
  - DOMAIN-SUFFIX,leetcode.com,Proxy
  - DOMAIN-SUFFIX,greasyfork.org,Proxy
  - DOMAIN-SUFFIX,wordhippo.com,Proxy
  - DOMAIN-SUFFIX,deepl.com,Proxy
  # ## 科学上网
  - DOMAIN-SUFFIX,v2rayse.com,Proxy
  - DOMAIN-SUFFIX,herokuapp.com,Proxy
  - DOMAIN-SUFFIX,bulink.xyz,Proxy
  - DOMAIN-SUFFIX,yugogo.xyz,Proxy
  - DOMAIN-SUFFIX,sspool.nl,Proxy
  - DOMAIN-SUFFIX,bihai.cf,Proxy
  - DOMAIN-SUFFIX,kingfu.cf,Proxy
  - DOMAIN-SUFFIX,swyjq.com,Proxy
  - DOMAIN-SUFFIX,hax.co.id,Proxy
  # ## 机场
  - DOMAIN-SUFFIX,mojie.me,Proxy
  - DOMAIN-SUFFIX,j20-cloud.me,Proxy
  - DOMAIN-SUFFIX,v2gyy.com,Proxy
  - DOMAIN-SUFFIX,welink345.com,Proxy
  # ## Common
  - DOMAIN-KEYWORD,speedtest,Proxy
  - DOMAIN-SUFFIX,rutracker.org,Proxy
  - DOMAIN-SUFFIX,truthsocial.com,Proxy
  - DOMAIN-SUFFIX,musclewiki.com,Proxy
  - DOMAIN-SUFFIX,limbopro.com,Proxy
  # ## Temp
  - DOMAIN-SUFFIX,lukesmith.xyz,Proxy
  - DOMAIN-SUFFIX,buyvm.net,Proxy
  - DOMAIN-SUFFIX,beautyleg.com,Proxy
  - DOMAIN-SUFFIX,ligui.org,Proxy

  # ## Clash rules
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,Proxy
  - RULE-SET,gfw,Proxy
  - RULE-SET,greatfire,Proxy
  - RULE-SET,telegramcidr,Proxy
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT

  # ## Rule mode
  - MATCH,RuleMode
