# Port of HTTP(S) proxy server on the local end
# port: 7890

# Port of SOCKS5 proxy server on the local end
# socks-port: 7891

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S) and SOCKS4(A)/SOCKS5 server on the same port
mixed-port: 7890

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: false

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
bind-address: '*'

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: info

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: false

# RESTful web API listening address
external-controller: 127.0.0.1:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
external-ui: yacd

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
# secret: ""

# Outbound interface name
# interface-name: en0

# Static hosts for DNS server and connection establishment (like /etc/hosts)
#
# Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names have a higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals to .foo.com and foo.com
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'

profile:
  # Store the `select` results in $HOME/.config/clash/.cache
  # set false If you don't want this behavior
  # when two different configurations have groups with the same name, the selected values are shared
  store-selected: true

# DNS server settings
# This section is optional. When not present, the DNS server will be disabled.

# ## tun
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    # ## 真实请求DNS
    - 114.114.114.114 # 真实请求DNS，可多设置几个
    # ## 国内服务器
    - 119.29.29.29    # 腾讯
    - 223.5.5.5       # 阿里
    - 180.76.76.76    # 百度
    # ## 真实请求DNS
    - 8.8.8.8
tun:
  enable: true
  stack: system # or gvisor
  dns-hijack:
  #   - 8.8.8.8:53
  #   - tcp://8.8.8.8:53
    - any:53
    - tcp://any:53
  auto-route: true # auto set global route
  auto-detect-interface: true # conflict with interface-name

proxy-groups:
  - name: "PROXY"
    type: select
    # disable-udp: true
    proxies:
      - AllFallback
      - AllSelect
      - SelectTor

  - name: "AllFallback"
    type: fallback
    use:
    proxies:
      - NodePoolAuto-z
    # tolerance: 50
    # lazy: true
    # url: 'http://www.gstatic.com/generate_204'
    url: 'https://www.google.com'
    interval: 30

  - name: "AllSelect"
    type: select
    # disable-udp: true
    use:
      - nodepool_myfilter-za
    proxies:

  - name: "SelectTor"
    type: select
    proxies:
      - tor
    # lazy: true
    # url: 'http://www.gstatic.com/generate_204'
    url: 'https://www.google.com'
    interval: 300

  - name: "NodePoolAuto-z"
    type: url-test
    use:
      - nodepool_myfilter-za
    proxies:
    # tolerance: 50
    # lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

proxies:
  - name: "tor"
    type: socks5
    server: 127.0.0.1
    port: 9150
    # username: username
    # password: password
    # tls: true
    # skip-cert-verify: true
    # udp: true

proxy-providers:
  nodepool_myfilter-za:
    type: http
    url: "https://proxies.bihai.cf/clash/proxies?filter=r"
    path: ./proxy-providers/nodepool/myfilter-za.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204

rules:
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - MATCH,PROXY
